config/routes.rb
Rails.application.routes.draw do

  resources :sub_channels
  resources :channels
  resources :buckets
  resources :events do
      resources :transactions
  end

  resources :books
  resources :transactions

  namespace :admin do
    root 'application#index'
  end
  root "static_pages#home"
  get "static_pages/help"

  post 'auth_user', to: 'authentication#authenticate_user'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  include Filterable
  has_many :transactions, inverse_of: :book
  scope :likeName, -> (name) { where("name like ?", "#{name}%")}
  scope :language, -> (language) {where language: language}


  def add_sold_count(quantity)
    self.lock!
    if available_count == 0
      Rails.logger.error "Available Count is nill"
    end
    self.sold_count += quantity
    self.save!
  end

  def sub_sold_count(quantity)
    self.lock!
    if available_count == 0
      Rails.logger.error "Available Count is nill"
    end
    if sold_count == 0
      Rails.logger.error "Trying to undo sale for a book that has not been sold #{@book} "
    end
    self.sold_count -= quantity
    self.save!
  end

  def update_available_count(quantity,reduce=true)
    self.lock!
    if(reduce)
      self.available_count -= quantity
    else
      self.available_count += quantity
    end
    self.save!
  end

  def update_total_count(quantity,reduce=true)
    self.lock!
    if(reduce)
      self.available_count -= quantity
      self.sold_count += quantity
    else
      self.available_count += quantity
      self.sold_count -= quantity
    end
    self.save!
  end

end

app/models/bucket.rb
class Bucket < ApplicationRecord
end

app/models/channel.rb
class Channel < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :transactions, inverse_of: :event, dependent: :delete_all
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/sub_channel.rb
class SubChannel < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :book, inverse_of: :transactions
  belongs_to :event, inverse_of: :transactions, optional: true
  enum activity: {sale: 0,consignment: 1,restock: 2, issue: 3, score: 4}
  enum status: {confirmed: 0, staged: 0}
  #validation
  validates :issued_by,:book_id,:activity,:status, presence: true
  validate :initial_count_greater_than_zero,:initial_count_less_than_end_count, if: :consigment?

  def move?
    activity == "move"
  end

  def consigment?
    activity == "consignment"
  end

  def initial_count_greater_than_zero
    if initial_count.nil? || initial_count < 0
      errors.add(:initial_count,"Initial count is less than zero or nil")
    end
  end

  def initial_count_less_than_end_count
    if initial_count < end_count
      errors.add(:end_count, "End count is more than intial count")
    end
  end

  def set_pending_amount
    pending_amount = sale_price - pending_amount
  end

end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/books_controller.rb
require 'csv'
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    render json: @books
  end

  # GET /books/1
  # GET /books/1.json
  def show
    render json: @book
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end


  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

      if @book.save
         render :show, status: :created, location: @book
      else
        render json: @book.errors, status: :unprocessable_entity
      end
  end

#  def upload
#    @file = books_param
#    csv = CSV.new(@file.to_io,{headers: true, header_converters: :symbol})
#    ProcessPricesJob.perform_later(csv)
#    print "Name of file #{@file.original_filename}"
#  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
      if @book.update(book_params)
        render json: @book
      else
        render json: @book.errors, status: :unprocessable_entity
      end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    render json: @book, status: :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.permit(:name, :code, :temple_price, :distributor_price, :reg_price, :language, :quantity,:available_count)
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    render json: @events
  end

  # GET /events/1
  # GET /events/1.json
  def show
    render json: @event
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
      if @event.save
         render json: @event, status: :created, location: @event
      else
        render json: @event.errors, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
      if @event.update(event_params)
        render json: @event, status: :ok, location: @event
      else
       render json: @event.errors, status: :unprocessable_entity
      end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    render json: { }, status: :ok

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
      @transactions = @event.transactions
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.permit(:name, :date, :location, :coordinator)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def admins_only(&block)
          block.call if current_user.try(:admin?)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/import_books_helper.rb
module ImportBooksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/sub_channels_helper.rb
module SubChannelsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <%= render "shared/navbar" %>
    <%= yield %>

  </body>
</html>

app/views/shared/_alert.html.erb
<div class="">
  <% flash.each do |key, value| %>
  <div class="callout small <%=key%>" data-closable>
    <%= value %>
    <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<!--
Foundation 6 navbar
-->


<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title">Menu</div>
</div>


<div class="top-bar" id="example-menu">
<ul class="vertical medium-horizontal menu">
  <% unless user_signed_in? %>
      <li>
        <%= link_to "Sign Up", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "Sign In", new_user_session_path %>
      </li>
  <% end %>
  <% if user_signed_in? %>
      <li>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      </li>
      <% admins_only do %>
          <li>
            <%= link_to "Admin Lounge", admin_root_path %>
          </li>
      <% end %>
      <li><%= link_to "Books", books_path %></li>
      <li><%= link_to "Transactions", transactions_path %></li>
      <li><%= link_to "Events", events_path %></li>
      <li class="menu-text">User: <%= current_user.email %></li>
  <% end %>
</ul>
</div>

<!--
<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">IMS</li>
      <% unless user_signed_in? %>
      <li>
        <%= link_to "Sign Up", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "Sign In", new_user_session_path %>
      </li>
      <% end %>
      <% if user_signed_in? %>
      <li>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      </li>
        <% admins_only do %>
          <li>
            <%= link_to "Admin Lounge", admin_root_path %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <% if user_signed_in? %>
    <div class="top-bar-right">
      <ul class="menu"><%= link_to "Books", books_path %></ul>
      <ul class="menu"><%= link_to "Transactions", transactions_path %></ul>
      <ul class="menu"><%= link_to "Events", events_path %></ul>
      <ul class="menu">
      <li class="menu-text">User: <%= current_user.email %></li>
      </ul>
    </div>
  <% end %>
</div>
-->