config/routes.rb
Rails.application.routes.draw do

  resources :sub_channels
  resources :channels
  resources :buckets
  resources :events do
      resources :transactions
  end

  resources :books
  resources :transactions

  namespace :admin do
    root 'application#index'
  end
  root "static_pages#home"
  get "static_pages/help"

  post 'auth_user', to: 'authentication#authenticate_user'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :transactions, inverse_of: :event, dependent: :delete_all
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    render json: @events
  end

  # GET /events/1
  # GET /events/1.json
  def show
    render json: @event
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
      if @event.save
         render json: @event, status: :created, location: @event
      else
        render json: @event.errors, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
      if @event.update(event_params)
        render json: @event, status: :ok, location: @event
      else
       render json: @event.errors, status: :unprocessable_entity
      end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    render json: { }, status: :ok

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
      @transactions = @event.transactions
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.permit(:name, :date, :location, :coordinator)
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>


  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :coordinator %>
    <%= f.text_field :coordinator %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_transaction.html.erb
<div class="row">
  <span class="small-12 hide-for-medium columns"> Book </span>
  <span class="small-12 large-2 columns"> <%=transaction.book.code%></span>
  <span class="small-12 hide-for-medium  columns"> Initial Count </span>
  <span class="small-12 large-2 columns"> <%=transaction.initial_count%></span>
  <span class="small-2 hide-for-medium  columns"> End Count </span>
  <span class="small-12 large-2 columns"> <%=transaction.end_count%></span>
  <span class="small-2 hide-for-medium  columns"> Quantity</span>
  <span class="small-12 large-2 columns"> <%=transaction.quantity%></span>
  <span class="small-2 hide-for-medium columns"> Status </span>
  <span class="small-12 large-2 columns"> <%=transaction.status%></span>
  <span class="small-12 large-2 columns"><a href="<%= event_transaction_path(event,transaction) %>"><%=fa_icon "folder-open" %></a>
    | <a href="<%= edit_event_transaction_path(event,transaction) %>"><%=fa_icon "edit" %></a> |
    <a data-confirm="Are you sure?" data-method="delete" href="<%= event_transaction_path(event,transaction) %>"><%=fa_icon "times" %></a>
  </span>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>



<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Location</th>
      <th>Coordinator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.date %></td>
        <td><%= event.location %></td>
        <td><%= event.coordinator %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<!--<p id="notice"><%= notice %></p>-->
<%= render "shared/alert" %>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Coordinator:</strong>
  <%= @event.coordinator %>
</p>

<div class="row">
  <div class="row">
    <span class="show-for-large-only large-2 columns"> Book </span>
    <span class="show-for-large-only large-2 columns"> Initial Count </span>
    <span class="show-for-large-only large-2 columns"> End Count </span>
    <span class="show-for-large-only large-2 columns"> Quantity</span>
    <span class="show-for-large-only large-2 columns"> Status </span>
    <span class="show-for-large-only large-2 columns">  </span>
  </div>
  <% if !@transactions.nil? %>
    <% @transactions.each do |transaction| %>
      <%= render 'transaction', transaction: transaction, event:@event %>
    <% end %>
  <%end%>
</div>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %> |
<%= link_to  'Add Books', new_event_transaction_path(@event) %>