config/routes.rb
Rails.application.routes.draw do

  resources :sub_channels
  resources :channels
  resources :buckets
  resources :events do
      resources :transactions
  end

  resources :books
  resources :transactions

  namespace :admin do
    root 'application#index'
  end
  root "static_pages#home"
  get "static_pages/help"

  post 'auth_user', to: 'authentication#authenticate_user'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bucket.rb
class Bucket < ApplicationRecord
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  before_action :set_bucket, only: [:show, :edit, :update, :destroy]

  # GET /buckets
  # GET /buckets.json
  def index
    @buckets = Bucket.all
    render json: @buckets
  end

  # GET /buckets/1
  # GET /buckets/1.json
  def show
    render json: @bucket
  end

  # GET /buckets/new
  def new
    @bucket = Bucket.new
  end

  # GET /buckets/1/edit
  def edit
  end

  # POST /buckets
  # POST /buckets.json
  def create
    @bucket = Bucket.new(bucket_params)
      if @bucket.save
        render json: @bucket, status: :created, location: @bucket
      else
        render json: @bucket.errors, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /buckets/1
  # PATCH/PUT /buckets/1.json
  def update
      if @bucket.update(bucket_params)
        render json: @bucket, status: :ok, location: @bucket
      else
        render json: @bucket.errors, status: :unprocessable_entity
      end
  end

  # DELETE /buckets/1
  # DELETE /buckets/1.json
  def destroy
    @bucket.destroy
      render json: @bucket, status: :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bucket
      @bucket = Bucket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bucket_params
      params.permit(:name)
    end
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/views/buckets/_form.html.erb
<%= form_for(bucket) do |f| %>
  <% if bucket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bucket.errors.count, "error") %> prohibited this bucket from being saved:</h2>

      <ul>
      <% bucket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buckets/edit.html.erb
<h1>Editing Bucket</h1>

<%= render 'form', bucket: @bucket %>

<%= link_to 'Show', @bucket %> |
<%= link_to 'Back', buckets_path %>

app/views/buckets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buckets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buckets.each do |bucket| %>
      <tr>
        <td><%= bucket.name %></td>
        <td><%= link_to 'Show', bucket %></td>
        <td><%= link_to 'Edit', edit_bucket_path(bucket) %></td>
        <td><%= link_to 'Destroy', bucket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bucket', new_bucket_path %>

app/views/buckets/new.html.erb
<h1>New Bucket</h1>

<%= render 'form', bucket: @bucket %>

<%= link_to 'Back', buckets_path %>

app/views/buckets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bucket.name %>
</p>

<%= link_to 'Edit', edit_bucket_path(@bucket) %> |
<%= link_to 'Back', buckets_path %>