config/routes.rb
Rails.application.routes.draw do

  resources :sub_channels
  resources :channels
  resources :buckets
  resources :events do
      resources :transactions
  end

  resources :books
  resources :transactions

  namespace :admin do
    root 'application#index'
  end
  root "static_pages#home"
  get "static_pages/help"

  post 'auth_user', to: 'authentication#authenticate_user'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :setup_trans_service, only: [:update]
  #before_action :set_event, :authenticate_user!
  before_action :authenticate_request!
  def create
      transaction_service = TransactionService.new(transaction_params, nil)
      status = transaction_service.create_transaction()
      @transactions = status[:transaction]
        if status[:success]
          render json: @transactions, status: :created, location: @transactions
        else
         render json: @transactions.errors, status: :unprocessable_entity
        end
  end

  def new
    @transactions = Transaction.new
  end

  def show
    render json: @transactions
  end

  def edit

  end

  def index
    @transactions = Transaction.all
    render json: @transactions, status: :ok
  end

  def update
    status = @transaction_service.update_transaction()
      if status[:success]
        render json: status[:transaction], status: :ok, location: @transactions
      else
        render json: @transactions.errors, status: :unprocessable_entity
      end


  end

  def destroy
    @transaction_service = TransactionService.new(nil,@transactions)
    status = @transaction_service.delete_transaction()
      if status[:success]
        render json: @transactions
      else
        render json: @transactions.errors, status: :unprocessable_entity
      end
  end


  private

  def transaction_params
    user_params = params.permit(:book_id,:quantity,:activity,:status,:origin_location,:final_location,:suggested_count,:initial_count,:end_count,:sale_price,:amount_paid)
    user_params = user_params.merge({issued_by: present_user.email})
    if(!event_id.nil?)
      user_params = user_params.merge({event_id: event_id})
    end
    user_params
  end

  def book_id
    params.permit(:book_id)
    params["book_id"]
  end

  def set_transaction
    @transactions = Transaction.find(params[:id])
  end

  def setup_trans_service
    @transaction_service = TransactionService.new(transaction_params,@transactions)
  end

  def set_event
    params.permit(:event_id)
    @event = params["event_id"].nil? ? nil: Event.find(params['event_id'])
  end

  def event_id
    params.permit(:event_id)
    Rails.logger.info("Event id is #{params["event_id"]}")
    params["event_id"]
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%=form_for(transaction, url: url) do |f|%>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %>
        prohibited this book from being saved:
      </h2>
      <ul>
        <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  <%= f.label :book %>
  <%= f.collection_select(:book_id, Book.all, :id, :code) %>
</div>

<div class="field">
  <%= f.label :activity %>
  <%= f.select(:activity, Transaction.activities.keys.map {|key| [key.capitalize,key]}, {}, onchange: "enableOptionalField(this)" ) %>
</div>

<div class=<%= transaction.consignment? ? "field" : "field_optional" %> >
  <%= f.label :suggested_count %>
  <%= f.number_field :suggested_count %>
</div>

<div class=<%= transaction.consignment? ? "field" : "field_optional" %> >
  <%= f.label :initial_count %>
  <%= f.number_field :initial_count %>
</div>

<div class=<%= transaction.consignment? ? "field" : "field_optional" %> >
  <%= f.label :end_count %>
  <%= f.number_field :end_count %>
</div>

<div class="field">
  <%= f.label :quantity %>
  <%= f.number_field :quantity %>
</div>

<div class="field">
  <%= f.label :status %>
  <%= f.select(:status, Transaction.statuses.keys.map {|key| [key.capitalize,key]}) %>
</div>

<div class="field">
  <%= f.label :sale_price %>
  <%= f.number_field :sale_price %>
</div>

<div class="field">
  <%= f.label :amount_paid %>
  <%= f.number_field :amount_paid %>
</div>

<div class="field">
  <%= f.label :pending_amount %>
  <%= f.number_field :pending_amount %>
</div>

<div class="field">
  <%= f.label :origin_location %>
  <%= f.text_field :origin_location %>
</div>

<div class="field">
  <%= f.label :final_location %>
  <%= f.text_field :final_location %>
</div>

<div class="field">
  <%= f.label :region %>
  <%= f.collection_select(:region, Region.all, :name, :name) %>
</div>

<div class="field">
  <%= f.label :bucket %>
  <%= f.collection_select(:bucket, Bucket.all, :name, :name) %>
</div>

<div class="field">
  <%= f.label :channel %>
  <%= f.collection_select(:channel, Channel.all, :name, :name) %>
</div>

<div class="field">
  <%= f.label :sub_channel %>
  <%= f.collection_select(:sub_channel, SubChannel.all, :name, :name) %>
</div>

<div class="field">
  <%= f.label :comments %>
  <%= f.text_field :comments %>
</div>

<div class="actions">
  <%= f.submit %>
</div>

<% end %>

app/views/transactions/edit.html.erb
<h1>Edit Transaction</h1>

<%= render 'form', transaction: @transactions, url: url_for([@event,@transactions]) %>
<%= link_to 'Show', @transactions %> |
<% if @event.nil? %>
<%= link_to 'Back', transactions_path %>
<% else %>
<%= link_to 'Back', event_path(@event) %>
<% end %>

app/views/transactions/index.html.erb
<h1>Transactions</h1>



<div class="tabs-content" data-tabs-content="example-tabs">
  <ul class="tabs" data-tabs id="example-tabs">
    <li class="tabs-title is-active"><a href="#panel1" aria-selected="true">General</a></li>
    <li class="tabs-title"><a href="#panel2">Consignment</a></li>
  </ul>
  <div class="table-scroll tabs-panel is-active" id="panel1">
    <table class="stack">
      <thead>
      <tr>
        <th>Date</th>
        <th>Book Code</th>
        <th>Activity</th>
        <th>Quantity</th>
        <th>Status</th>
        <th>Event</th>
        <th>Bucket</th>
        <th>Channel</th>
        <th>SubChannel</th>
        <th colspan="3"></th>
      </tr>
      </thead>
      <tbody>
      <% @transactions.select{|trans| !trans.consigment?}.each do |transaction| %>
          <tr>
            <td class="hide-for-large">Date:</td>
            <td><%=transaction.updated_at.to_date %></td>
            <td class="hide-for-large">Code:</td>
            <td><%=transaction.book.code %></td>
            <td class="hide-for-large">Activity:</td>
            <td><%=transaction.activity %></td>
            <td class="hide-for-large">Quantity:</td>
            <td><%=transaction.quantity%></td>
            <td class="hide-for-large">Status:</td>
            <td><%=transaction.status%></td>
            <td class="hide-for-large">Event:</td>
            <td><%=transaction.event.nil? ? "" : transaction.event.name %></td>
            <td class="hide-for-large">Bucket:</td>
            <td><%=transaction.bucket%></td>
            <td class="hide-for-large">Channel:</td>
            <td><%=transaction.channel%></td>
            <td class="hide-for-large">SubChannel:</td>
            <td><%=transaction.sub_channel%></td>
            <td><a href="<%= transaction_path(transaction.id) %>"><%=fa_icon "folder-open" %></a>
            | <a href="<%= edit_transaction_path(transaction.id) %>"><%=fa_icon "edit" %></a> |
              <a data-confirm="Are you sure?" data-method="delete" href="<%= transaction_path(transaction.id) %>"><%=fa_icon "times" %></a>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="table-scroll tabs-panel is-active" id="panel2">
    <table class="stack">
      <thead>
      <tr>
        <th>Date</th>
        <th>Book Code</th>
        <th>Suggested Count</th>
        <th>Initial Count</th>
        <th>End Count</th>
        <th>Quantity</th>
        <th>Status</th>
        <th>Event</th>
        <th>Bucket</th>
        <th>Channel</th>
        <th>SubChannel</th>
        <th colspan="3"></th>
      </tr>
      </thead>
      <tbody>
      <% @transactions.select{|trans| trans.consignment?}.each do |transaction| %>
          <tr>
            <td class="hide-for-large">Date:</td>
            <td><%=transaction.updated_at.to_date %></td>
            <td class="hide-for-large">Code:</td>
            <td><%=transaction.book.code %></td>
            <td class="hide-for-large">Suggested Count:</td>
            <td><%=transaction.suggested_count%></td>
            <td class="hide-for-large">Initial Count:</td>
            <td><%=transaction.initial_count%></td>
            <td class="hide-for-large">End Count:</td>
            <td><%=transaction.end_count%></td>
            <td class="hide-for-large">Quantity:</td>
            <td><%=transaction.quantity%></td>
            <td class="hide-for-large">Status:</td>
            <td><%=transaction.status%></td>
            <td class="hide-for-large">Event:</td>
            <td><%=transaction.event.nil? ? "" : transaction.event.name %></td>
            <td class="hide-for-large">Bucket:</td>
            <td><%=transaction.bucket%></td>
            <td class="hide-for-large">Channel:</td>
            <td><%=transaction.channel%></td>
            <td class="hide-for-large">SubChannel:</td>
            <td><%=transaction.sub_channel%></td>
            <td><a href="<%= transaction_path(transaction.id) %>"><%=fa_icon "folder-open" %></a>
              | <a href="<%= edit_transaction_path(transaction.id) %>"><%=fa_icon "edit" %></a> |
              <a data-confirm="Are you sure?" data-method="delete" href="<%= transaction_path(transaction.id) %>"><%=fa_icon "times" %></a>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>
<%= render "shared/alert" %>

<%= render 'form', transaction: @transactions, url: url_for([@event,@transactions]) %>

app/views/transactions/show.html.erb
<h1>Transaction</h1>
<%= render "shared/alert" %>

<div class="">
  <p>
    <span>Book Code</span>
    <%= @transactions.book.code %>
  </p>
  <p>
    <span>quantity</span>
    <%= @transactions.quantity %>
  </p>
  <p>
    <span>Issued By</span>
    <%= @transactions.issued_by %>
  </p>
  <p>
    <span>Created Time</span>
    <%= @transactions.created_at %>
  </p>
  <p>
    <span>Updated Time</span>
    <%= @transactions.updated_at %>
  </p>
</div>
<% if @event.nil? %>
<%= link_to 'Transactions', transaction_url %> |
<%= link_to 'Edit', edit_transaction_path(@transactions)%>
<% else %>
<%= link_to @event.name, event_path(@event) %> |
<%= link_to 'Edit', edit_event_transaction_path(@event,@transactions)%>
<% end %>